// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoyAKxnZDaYXvOKOeR73-wjgBloCX35GM',
    appId: '1:1043492351226:web:37ad2f6a9eee45e893ad43',
    messagingSenderId: '1043492351226',
    projectId: 'cookingcompaniondb',
    authDomain: 'cookingcompaniondb.firebaseapp.com',
    storageBucket: 'cookingcompaniondb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUeTTwbY78fgFFqWJ5DDnXUfAX8RWKsME',
    appId: '1:1043492351226:android:ec18e6bcf667c55693ad43',
    messagingSenderId: '1043492351226',
    projectId: 'cookingcompaniondb',
    storageBucket: 'cookingcompaniondb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTfZ6iIDV1qd2gpablXTClX8_3oFTK0fQ',
    appId: '1:1043492351226:ios:d3f78e341b89551493ad43',
    messagingSenderId: '1043492351226',
    projectId: 'cookingcompaniondb',
    storageBucket: 'cookingcompaniondb.firebasestorage.app',
    iosBundleId: 'com.example.recipenook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTfZ6iIDV1qd2gpablXTClX8_3oFTK0fQ',
    appId: '1:1043492351226:ios:d3f78e341b89551493ad43',
    messagingSenderId: '1043492351226',
    projectId: 'cookingcompaniondb',
    storageBucket: 'cookingcompaniondb.firebasestorage.app',
    iosBundleId: 'com.example.recipenook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoyAKxnZDaYXvOKOeR73-wjgBloCX35GM',
    appId: '1:1043492351226:web:e84313189a350caa93ad43',
    messagingSenderId: '1043492351226',
    projectId: 'cookingcompaniondb',
    authDomain: 'cookingcompaniondb.firebaseapp.com',
    storageBucket: 'cookingcompaniondb.firebasestorage.app',
  );
}
